/* Auto-generated by cbindgen. Do not edit manually. */
/*
 * ragfs_ffi.h — C FFI header for ragfs (LocalFileSystem)
 *
 * Embed ragfs into C / Go / other languages via cgo. The exported ABI uses
 * the `viking_*` prefix (canonical OpenViking naming); the staticlib name
 * `libragfs_ffi.a` (Linux/macOS) / `ragfs_ffi.lib` (Windows MSVC) is unchanged
 * for compatibility with the existing release artifacts.
 *
 * Lifecycle:
 *   1. viking_fs_open(base_path)  → opaque handle
 *   2. viking_fs_get / put / mkdir / delete / list
 *   3. viking_fs_close(handle)
 *
 * On any error, call viking_last_error() to get a thread-local message.
 * All malloc-allocated buffers (strings / byte arrays) must be freed with
 * viking_free().
 */

#ifndef RAGFS_FFI_H
#define RAGFS_FFI_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Open a ragfs LocalFileSystem rooted at `base_path`.
 * Returns an opaque handle, or NULL on error (check viking_last_error).
 *
 * base_path must be a valid NUL-terminated C string.
 */
void *viking_fs_open(const char *base_path);

/**
 * Close and free a handle returned by viking_fs_open.
 * handle must come from viking_fs_open and be used at most once.
 */
void viking_fs_close(void *handle);

/**
 * Read a file's contents.
 * Returns a malloc-allocated byte buffer (or NULL for empty/missing file);
 * *out_len receives the byte count. Caller must viking_free() the buffer.
 */
void *viking_fs_get(void *handle, const char *path, uint64_t *out_len);

/**
 * Write a file's contents. Auto-creates parent directories.
 * Returns 0 on success, non-zero on error.
 */
int viking_fs_put(void *handle, const char *path, const void *data, size_t len);

/**
 * Create a single directory.
 * Returns 0 on success (including if the directory already exists),
 * non-zero on other errors.
 */
int viking_fs_mkdir(void *handle, const char *path, int mode);

/**
 * Delete a file.
 * Returns 0 on success, non-zero on error.
 */
int viking_fs_delete(void *handle, const char *path);

/**
 * List a directory.
 * Returns a malloc-allocated UTF-8 JSON array of {"name","size","is_dir"},
 * or NULL on error. Caller must viking_free() the returned string.
 */
char *viking_fs_list(void *handle, const char *path);

/**
 * Get the most recent error message (thread-local).
 * Returns a C string valid until the next viking_* call on this thread.
 */
const char *viking_last_error(void);

/**
 * Free a buffer previously returned by viking_fs_* (strings or byte arrays).
 */
void viking_free(void *ptr);

#ifdef __cplusplus
}
#endif

#endif /* RAGFS_FFI_H */
